### ISSUE TITLE
Live streaming feature

### ISSUE THREAD

**Issue by mkstmyk** [ittybittyapps/ARRecorder#3]
Hi Vlas,
Thank you for your great work. I also run and enjoyed your AR Visualizer. In the demo video, you streamed the recorded session to a Mac for visualization. Is this feature already included in the repo? If so, how can I activate it? If not, do you have a plan to update it with the feature?
Thank you.

**Comment by vlas-voloshin** [comment]
Hello, and thanks for the kind words!
The demos you've seen essentially combine the functionality of the two repos, but unfortunately this combination is not included in either one at the moment. We don't have particular plans for making it available "out of the box", but you can replicate it fairly easily: start with the Visualiser, and put the relevant bits of the Recorder into the Server target, which runs the ARKit session, alongside with any UI to help you control it. For the purposes of streaming the session data to the Visualiser, a "live" AR session and a recorded one behave exactly the same, so there's no other special code you'd need to write to enable streaming a recorded session. Good luck!

**Comment by mkstmyk** [comment]
Thank you so much for your suggestion. I've just get back to work on this. Please allow me to ask some more.
I might be wrong, but it seems that I have to put relevant bits of the Recorder into the Client, or put some parts of the Client into the Recorder, because a live session and a recorded one are all the same to the Visualizer as you explained.
I appreciate if you give me some more details to integrate them. Thank you.

**Comment by mkstmyk** [comment]
Hi Vlas, 
Thanks to your kind suggestions, I succeeded in integrating the Recorder feature to the Visualizer. As your code is very well-organized, it was easy to do that. Do you mind me creating its branch here?

**Comment by orj** [comment]
Hi folks, :wave: unfortunately we are not actively maintaining this project. 

Apple are free to change their private SPI at any time so supporting projects that use private SPI can be difficult. We've chosen to archive this project but that doesn't mean it couldn't be modified to work with newer OS releases given enough spelunking through API's private SPI.

Please feel free to fork and resurrect this code if you want to give that a try. 

Thanks 🙏
