### ISSUE TITLE
How to add time metadata track in recorded video

### ISSUE THREAD

**Issue by Rthangavel** [ittybittyapps/ARRecorder#4]
how to add the time metadata track into the video where recorded from private api.

**Comment by orj** [comment]
Hi folks, :wave: unfortunately we are not actively maintaining this project. 

Apple are free to change their private SPI at any time so supporting projects that use private SPI can be difficult. We've chosen to archive this project but that doesn't mean it couldn't be modified to work with newer OS releases given enough spelunking through API's private SPI.

Please feel free to fork and resurrect this code if you want to give that a try. 

Thanks 🙏
