### ISSUE TITLE
iOS13 changes

### ISSUE THREAD

**Issue by germanleiva** [ittybittyapps/ARRecorder#5]
It seems that this API changed in iOS13 but should be available (e.g., Reality Composer is using recording for Xcode debugging).

Is there still a way of accessing it?

**Comment by orj** [comment]
Good question. @vlas-voloshin have you looked into this?

**Comment by vlas-voloshin** [comment]
Sorry, I haven't been investigating this area lately. I presume it either uses different class/method names now, or has been possibly moved into RealityKit.

**Comment by germanleiva** [comment]
Thanks for the answers. 

I used the RuntimeBrowser https://github.com/leptos-null/RuntimeBrowser on iOS13 and it seems that the same classes/methods are still within the ARKit framework. There are new classes and few variations, for example ARRecordingTechnique now implements ARRecordingTechniqueProtocol. 

I will try to pinpoint the breaking difference by comparing the behavior in iOS12 vs iOS13 but any help is welcomed.

**Comment by Rthangavel** [comment]
This technique not working in ARKit3 supported devices. Is any alternate?

**Comment by AndrewHartAR** [comment]
Implementing the changes that Germán mentioned, on iOS I'm able to playback videos recorded using iOS 12, but not videos recorded using iOS 13. Not sure why it might be treating those differently. I've attached a zip of the updated project.

[ARRecorder-iOS13.zip](https://github.com/ittybittyapps/ARRecorder/files/3735033/ARRecorder-iOS13.zip)

**Comment by AndrewHartAR** [comment]
Logs from running an iOS 13 video, and then an iOS 12 video:

```
did finish loading frames: 0
did finish loading with start timestamp: 0.0, end timestamp: 7.3966666666666665
did finish replaying data

did finish loading frames: 1758
did finish loading with start timestamp: 1.0116666666666667, end timestamp: 59.63666666666667
did finish replaying data
```

Clearly there's some difference in its interpretation of the two files, when it considers the iOS 13 video to have 0 frames.

**Comment by AndrewHartAR** [comment]
@orj or @tonyarnold - any thoughts on how to resolve this for iOS 13?

**Comment by tonyarnold** [comment]
@ProjectDent I'm not likely to have time to search for where the APIs moved to until closer to the end of the year (and @orj is usually busier than I am).

As others have said, it does seem like the SPI is still available in the frameworks _somewhere_ given that Xcode is using them, but there's no guarantee they're going to be accessible.

**Comment by AndrewHartAR** [comment]
@tonyarnold thanks for taking a look here - wondered if there's been any progress on looking into this? would massively help our current process, but I don't know what I'm doing here.

**Comment by AndrewHartAR** [comment]
@tonyarnold wonder if you had an opportunity to look into this yet?

**Comment by tonyarnold** [comment]
@ProjectDent I have not, no.

**Comment by AndrewHartAR** [comment]
Any resources you could suggest for me to learn how to pick out those APIs myself would be very helpful.

**Comment by vlas-voloshin** [comment]
@ProjectDent I've taken a look at the SPI changes in iOS 13, changes described by @germanleiva and your updated project, and I believe the issues you're having come from not using the right replay sensor class. It's not enough just to rename `ARReplaySensor.h` to `ARReplaySensorPublic.h` – that won't have any effect, you need to use the new `ARReplaySensorPublic` class introduced in iOS 13. Luckily, its interface is largely the same as for the older `ARReplaySensor` (which I'd treat as deprecated), and in fact there's now a common protocol `ARReplaySensorProtocol` that they both conform to.
I've been able to update the SPI headers (with some help from [this website](http://developer.limneos.net/index.php?ios=13.1.3&framework=ARKit.framework) and, as usual, [Hopper Disassembler](https://www.hopperapp.com)), and successfully replayed a recording made on iOS 13. I'll make a PR shortly.
