### ISSUE TITLE
Recording multiple sessions

### ISSUE THREAD

**Issue by fbobital** [ittybittyapps/ARRecorder#8]
The current version only records the first ARKit session. When I tried to record the second session, the app doesn't save the output file in the `Documents` directory. I have to close the application and open it again to save the next session. Does anyone face the same error?

**Comment by fbobital** [comment]
Another interesting information. This morning, I tested the application using an iPhone X with iOS 13.5.1. It works perfectly. I could save up to 5 sessions in sequence. The problem is using an iPad Pro (11-inch) with iOS 13.5.1. I've updated the iPad to iOS 13.6 (17G68), but it isn't possible to save more than one ARKit session.

**Comment by orj** [comment]
Hi folks, :wave: unfortunately we are not actively maintaining this project. 

Apple are free to change their private SPI at any time so supporting projects that use private SPI can be difficult. We've chosen to archive this project but that doesn't mean it couldn't be modified to work with newer OS releases given enough spelunking through API's private SPI.

Please feel free to fork and resurrect this code if you want to give that a try. 

Thanks 🙏
