### ISSUE TITLE
ios14 Support?

### ISSUE THREAD

**Issue by melvinma** [ittybittyapps/ARRecorder#9]
I wonder if you could publish a version with ios14 support. Thanks.

**Comment by melvinma** [comment]
I was trying to build it for ios14 (by setting deploy target to ios14), that is not officially released. I got "link error" saying **undefined symbols**, **_OBJ_CLASS_$_ARReplaySensorPublic, ARReplaySensor, ARRecordingTechnique** are not found. I wonder if Apple removed those APIs - I am not sophisticated enough to be able to search ios14 header files. What is the alternatives in ios14? Thank you very much! Really appreciate your help.

**Comment by melvinma** [comment]
none issue.

**Comment by melvinma** [comment]
Well, I was not able to solve the issue of how to run this code in iOS 14. Any help is appreciated.

**Comment by melvinma** [comment]
`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_ARRecordingTechnique", referenced from:
      objc-class-ref in MainViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by melvinma** [comment]
Just found out that this issue is related to XCode Beta. Same code works in XCode.

**Comment by melvinma** [comment]
I might find out the reason why -

if run `grep -R "ARRecordingTechnique" <dir> `  against iOS 13 vs iOS 14, there is a difference -

on XCode official release  (iOS 13), I got 
```
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform//Developer/SDKs/iPhoneOS13.7.sdk/System/Library/Frameworks/ARKit.framework/ARKit.tbd:                       ARRecordingConfiguration, ARRecordingTechnique, ARRecordingTechniquePublic, 
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform//Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/ARKit.framework/ARKit.tbd:                       ARRecordingConfiguration, ARRecordingTechnique, ARRecordingTechniquePublic, 
```

on XCode Beta (iOS 14), I got
`./iPhoneOS.sdk/System/Library/PrivateFrameworks/ARKitCore.framework/ARKitCore.tbd:                       ARRecordingTechniquePublic, ARReferenceImage, ARReferenceImageCachedError, 
./iPhoneOS.sdk/System/Library/Frameworks/ARKit.framework/ARKit.tbd:                       ARRecordingTechniquePublic, ARReferenceImage, ARReferenceObject, 
./iPhoneOS14.0.sdk/System/Library/PrivateFrameworks/ARKitCore.framework/ARKitCore.tbd:                       ARRecordingTechniquePublic, ARReferenceImage, ARReferenceImageCachedError, 
./iPhoneOS14.0.sdk/System/Library/Frameworks/ARKit.framework/ARKit.tbd:                       ARRecordingTechniquePublic, ARReferenceImage, ARReferenceObject, `
 
Clearly header file ARRecordingTechnique was in iOS 13  but not in iOS 14. 

Please help!

**Comment by johannesd** [comment]
Same problem here.

**Comment by haydar-fm** [comment]
Any information on this?

**Comment by beaol** [comment]
I am experiencing the same issues when trying to run the program on my iPad Pro which runs on IOS version 14.3
Has anyone found a solution to this problem?

**Comment by dzeitman** [comment]
Any updates on this issue?   I'd like to use with IOS 14.x

**Comment by noreengao0924** [comment]
same here with the IOS 14 problem

**Comment by saurabh1939** [comment]
Any update on this ?

**Comment by orj** [comment]
Hi folks, :wave: unfortunately we are not actively maintaining this project. 

Apple are free to change their private SPI at any time so supporting projects that use private SPI can be difficult. We've chosen to archive this project but that doesn't mean it couldn't be modified to work with newer OS releases given enough spelunking through API's private SPI.

Please feel free to fork and resurrect this code if you want to give that a try. 

Thanks 🙏
